wandb_version: 1

batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.005
neurons1:
  desc: null
  value: 21
neurons2:
  desc: null
  value: 28
neurons3:
  desc: null
  value: 64
optimizer:
  desc: null
  value: adam
_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.15.12
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1699114055.701292
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 3
      - 8
      - 19
      - 23
      - 37
      4: 3.11.6
      5: 0.15.12
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
architecture_name:
  desc: null
  value: V01
dataset_name:
  desc: null
  value: MNIST
