wandb_version: 1

batch_size:
  desc: null
  value: 200
epochs:
  desc: null
  value: 20
learning_rate:
  desc: null
  value: 0.007
neurons1:
  desc: null
  value: 31
neurons2:
  desc: null
  value: 11
neurons3:
  desc: null
  value: 78
optimizer:
  desc: null
  value: adam
_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.15.12
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1699127647.722554
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 3
      - 8
      - 19
      - 23
      - 37
      4: 3.11.6
      5: 0.15.12
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
architecture_name:
  desc: null
  value: V01
dataset_name:
  desc: null
  value: MNIST
